apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app3
  labels:
    app: springboot-app3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app3
  template:
    metadata:
      labels:
        app: springboot-app3
    spec:
      containers:
      - name: springboot-app3
        image: hdxt25/springboot-app3:f003bef7771c71662efd0104071483f4adaf1428
        ports:
        - containerPort: 8080
